ebook_metadata:
  title: ༄༅༅། །ཉེར་མཁོ་ཐོར་བུ་སྣ་ཚོགས་ཀྱི་སྐོར་ལྷག་པའི་ལྷ་སྣ་ཚོགས་ཀྱི་སྒྲུབ་ཐབས་དང་བསྙེན་ཡིག་སོགས་ཀྱི་སྐོར་ཉེར་མཁོའི་དབང་གི་མཚམས་སྦྱོར་སྣ་ཚོགས་པ་བཅས།
    །
  authors:
  - མཛད་པ་པོ། ཞེ་ཆེན་རྒྱལ་ཚབ་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ།
  sku: SHE-SG-12
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - sabche
  - yigchung
web_metadata:
  title:
    en: Various Sadhanas and Empowerment Rituals
    bo: སྒྲུབ་ཐབས་དང་དབང་ཉེར་མཁོ་སྣ་ཚོགས།༼ན༽
  collection:
    en: Shechen Gyaltsab Series–  Book 12
    bo: ཞེ་ཆེན་རྒྱལ་ཚབ་གསུང་འབུམ།–  དེབ། ༡༢
  author:
    en: Shechen Gyaltsap Gyurme Pema Namgyal
    bo: ཞེ་ཆེན་རྒྱལ་ཚབ་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SG-12
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SG-12.epub
  description:
    en: ''
    bo: ''
